const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const Article = require('../backend/models/Article');

const articles = [
  {
    title: 'The Silent Whispers of the Oak Woods',
    content: 'Deep in the heart of the ancient Oak Woods, where the sun barely touches the forest floor, lived a young boy named Elian. He possessed a rare gift: the ability to hear the trees speak.\n\nWhile others heard only the rustling of leaves, Elian heard stories of centuries past, of forgotten kings and mythical creatures.\n\nOne evening, the great Oak at the center of the woods began to tremble. Its roots vibrated with a sense of urgency. "Elian," it whispered in a voice that sounded like grinding stone, "the shadows are lengthening. Something that was locked away is waking up."\n\nElian knew exactly what the tree meant. Legends told of the Obsidian Shadow, a creature born from the absence of light, which had been imprisoned beneath the forest floor by the first druids. If it escaped, the entire world would fall into an eternal slumber.\n\nGuided by the whispers of the woods, Elian set out on a journey to the Silver Waterfall, where the only weapon against the shadow—the Prism of Dawn—was hidden. He navigated through treacherous swamps and climbed jagged cliffs, always listening for the guidance of the trees.\n\nWhen he finally reached the waterfall, a guardian made of pure ice stood in his way. "Only one with a heart as clear as morning dew may pass," it declared. Elian stood tall, his heart and mind focused on protecting the forest he loved.\n\nWith a nod, the guardian stepped aside, revealing a small, glowing crystal. This was the Prism of Dawn. As Elian grasped it, a surge of warmth filled his body. He raced back to the great Oak, just as the first tendrils of the Obsidian Shadow began to seep through the ground.\n\nRaising the prism high, Elian channeled all his courage into the stone. A blinding beam of pure golden light erupted from the crystal, striking the center of the shadow. The forest echoed with a deafening roar as the darkness was drawn back into the earth, sealed once more.\n\nThe trees stood still, their leaves shimmering in the soft moonlight. "You have saved us, child of the woods," the great Oak hummed peacefully. From that day on, Elian was known as the Guardian of the Whispers, the one who kept the shadows at bay.',
    coins: 15,
    readingTime: 45
  },
  {
    title: 'The Clockwork City of Aethelgard',
    content: 'Aethelgard was a city like no other. Built entirely from brass, copper, and steam, its streets were a maze of cogs and gears that moved in perfect harmony. The citizens were masterpieces of engineering, their lives governed by the tick-tock of the central Great Clock.\n\nLyra, a young apprentice clockmaker, noticed something unusual one morning. The rhythm of the city felt slightly off. A small gear near the South Gate was spinning backward, a phenomenon that should have been physically impossible in the structured world of Aethelgard.\n\nShe reported her finding to the High Artificer, but he dismissed her concerns. "The Great Clock is infallible," he insisted, his own metallic eyes clicking in annoyance. But Lyra knew that even the most perfect machines could have hidden flaws.\n\nThat night, she snuck into the heart of the Great Clock itself. The internal chamber was a cathedral of motion, with pendulum swings that echoed like heartbeats. As she climbed the central pillar, she found the source of the malfunction: a small, biological spider had spun a web between the main escapement and the winding barrel.\n\nIn a city of cold metal, this tiny living creature was an anomaly. But it wasn\'t just a spider; it was glowing with a strange, bioluminescent light. Every time the spider pulled a thread of its web, the gears shifted in ways they weren\'t designed to.\n\nLyra realized that the spider was actually manipulating the flow of time within Aethelgard. The backward-spinning gear was just the beginning. If the spider continued, the entire city would eventually be erased from history, its gears uncurling back into raw ore.\n\nInstead of removing the spider, Lyra began to communicate with it, mimicking the vibrations of its web on her own tiny tuning forks. She learned that the spider was a traveler from a different dimension, lost and trying to find its way home through the city’s mechanical vibrations.\n\nUsing her skills, Lyra built a bridge of brass and crystal that harmonized with the spider’s home world. With a final pulse of light, the creature vanished, leaving the gears of Aethelgard to return to their normal, steady rhythm.\n\nLyra never told anyone what she had found. She remained an apprentice, but every time she heard the chime of the Great Clock, she smiled, knowing that sometimes, even the most rigid world needs a little bit of unexpected life.',
    coins: 15,
    readingTime: 45
  },
  {
    title: 'The Star-Baker of the Nebula',
    content: 'In the swirling colorful clouds of the Orion Nebula lived Orion, the Star-Baker. While others explored galaxies or mapped black holes, Orion spent his days in a kitchen made of stardust, kneading dough from cosmic dust and sweetening it with the essence of old stars.\n\nHis specialty was the Moon-Drop Cookie, a delicacy that could grant a person the ability to dream in full color. Every thousand years, Orion held a grand feast where travelers from across the universe gathered to taste his creations.\n\nOne cycle, a weary traveler from the edge of the Void arrived at his doorstep. She was a Shadow-Wanderer, a being who had never known light or warmth. "I have heard that your treats can bring life to the coldest of souls," she whispered.\n\nOrion looked at her fading form and knew he had to create something special. He didn\'t reach for his usual ingredients. Instead, he gathered the first breath of a new nebula, the laughter of a comet, and the unwavering hope of a lonely planet.\n\nHe baked the bread in the core of a dying star, letting it soak up every last bit of warmth. When it was finished, the loaf glowed with a soft, comforting heat that felt like a hug from the universe itself.\n\nThe Shadow-Wanderer took a bite, and for the first time in eons, she felt a heartbeat. A soft color began to bloom in her translucent skin—a deep, vibrant purple like the very nebula they were in. She wasn\'t just a shadow anymore; she was a part of the cosmos.\n\n"Thank you, Orion," she said, her voice no longer a whisper. "You have given me a story to carry back to the darkness." Orion simply smiled, wiping flour from his hands and looking out at the endless expanse of stars.\n\nHe knew that his work was more than just baking; it was about weaving connections across the vast loneliness of space. As long as there were those in need of light, the Star-Baker would always have his oven ready, turning the dust of the universe into something truly magical.',
    coins: 15,
    readingTime: 45
  },
  {
    title: 'The Librarian of the Sunken Kingdom',
    content: 'Beneath the turbulent waves of the Emerald Sea lay the kingdom of Thalassa, a city of coral and pearl that had long been forgotten by the surface world. Its most precious treasure was the Great Library, where every book was written on scales of ancient sea serpents.\n\nMarina was the librarian of this underwater sanctuary. Her job was to keep the records dry using magical air bubbles and to ensure that the secrets of the deep remained safe from curious adventurers. But Marina herself was the most curious of all.\n\nShe often spent her hours reading about the surface—of forests that changed color with the seasons and of mountains that touched the sky. To her, these stories were as mystical as the deep-sea trenches were to those above.\n\nOne day, a heavy iron chest sank from a passing ship and landed right in front of the library gates. Inside, Marina found something she had only ever seen in illustrations: a collection of dried flowers and a map leading to the legendary Peak of Solitude.\n\nShe realized this wasn\'t just rubbish; it was a call to adventure. But a mermaid could not leave the sea, just as a mountain-dweller could not live in the depths. Marina looked at the dried petals, their colors faded but their beauty still evident.\n\nDetermined to share the wonders of the deep with the world above, she began to write her own books. She used the brightest bioluminescent ink to describe the dance of the jellyfish and the songs of the blue whales. She wrote of the kindness of the dolphins and the wisdom of the old turtles.\n\nShe packed her stories into waterproof glass spheres and let them float to the surface. For years, she sent her messages upward, hoping that someone, somewhere, would find them and understand that they weren\'t alone in the world.\n\nEventually, her stories became legends on the surface. People spoke of the Whispering Waves and the Treasures of Thalassa. Marina never saw the forests or the mountains, but she knew that her words had reached them, bridging the gap between two worlds.\n\nHer library grew, not just with the scales of serpents, but with the dreams of those who stood on the shore, looking out at the horizon. Marina was no longer just a librarian; she was proof that no matter how deep you are, your voice can always find its way to the light.',
    coins: 15,
    readingTime: 45
  },
  {
    title: 'The Inventor of Forgotten Memories',
    content: 'Silas lived in a small workshop at the edge of a village where people went to forget. He was an inventor, but he didn\'t build machines or gadgets. He built Memory-Keepers—small, intricate music boxes that could hold a single, precious moment.\n\nIn a world where time moved too fast, people often lost track of their happiest days. They would visit Silas, handing him a fragment of a feeling—the smell of rain on hot pavement, the sound of a loved one’s laughter, or the warmth of a childhood home.\n\nSilas would carefully trap these essences in gears of silver and springs of gold. When the box was wound, the memory would play back in the listener\'s mind, as vivid as the day it happened. It was a service of immense kindness, but Silas himself had no memory-keeper of his own.\n\nOne afternoon, an old woman named Clara arrived. "I have nothing left to give you," she said sadly. "I have forgotten everything except the fact that I once had a memory worth keeping."\n\nSilas looked into her eyes and saw a deep, aching emptiness. He decided to do something he had never done before. He began to build a music box using his own memories. He put in the joy he felt when he finished his first invention, the peace of a quiet sunrise, and the satisfaction of helping his neighbors.\n\nHe worked through the night, his house filled with the clinking of metal. When the sun began to peek over the horizon, he handed the finished box to Clara. "This is not your memory," he said softly. "But I hope it will help you find your own."\n\nAs Clara wound the box and listened to the melody, a small tear rolled down her cheek. The emptiness in her eyes began to flicker with light. She didn\'t remember her past, but she felt the possibility of a future. She realized that memories aren\'t just about what happened; they are about the capacity to feel.\n\nShe thanked Silas and left, her step lighter than it had been in years. Silas sat back in his chair, watching the dust motes dance in the sunlight. He had given away a part of himself, but in doing so, he had discovered the greatest memory of all: the moment he realized that kindness is the only thing truly worth remembering.\n\nHis workshop remained a place of solace, a quiet corner of the world where time slowed down just enough for people to find themselves again. And although Silas still had no box for himself, his heart was full, echoing with the melodies of a thousand happy lives.',
    coins: 15,
    readingTime: 45
  }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');
    
    await Article.deleteMany({});
    console.log('Cleared existing articles');
    
    await Article.insertMany(articles);
    console.log('Successfully seeded 5 premium articles');
    
    process.exit(0);
  } catch (err) {
    console.error('Error seeding articles:', err);
    process.exit(1);
  }
}

seed();
