export const countries = [
  { id: 'USA', name: 'United States', flag: '🇺🇸', iso: 'us' },
  { id: 'GBR', name: 'United Kingdom', flag: '🇬🇧', iso: 'gb' },
  { id: 'CAN', name: 'Canada', flag: '🇨🇦', iso: 'ca' },
  { id: 'DEU', name: 'Germany', flag: '🇩🇪', iso: 'de' },
  { id: 'AUS', name: 'Australia', flag: '🇦🇺', iso: 'au' },
  { id: 'JPN', name: 'Japan', flag: '🇯🇵', iso: 'jp' },
  { id: 'SGP', name: 'Singapore', flag: '🇸🇬', iso: 'sg' },
  { id: 'IND', name: 'India', flag: '🇮🇳', iso: 'in' },
  { id: 'BGD', name: 'Bangladesh', flag: '🇧🇩', iso: 'bd' },
  { id: 'PAK', name: 'Pakistan', flag: '🇵🇰', iso: 'pk' },
  { id: 'ARE', name: 'UAE', flag: '🇦🇪', iso: 'ae' },
  { id: 'KSA', name: 'Saudi Arabia', flag: '🇸🇦', iso: 'sa' },
  { id: 'MYS', name: 'Malaysia', flag: '🇲🇾', iso: 'my' },
  { id: 'QAT', name: 'Qatar', flag: '🇶🇦', iso: 'qa' },
  { id: 'ITA', name: 'Italy', flag: '🇮🇹', iso: 'it' },
  { id: 'FRA', name: 'France', flag: '🇫🇷', iso: 'fr' },
  { id: 'NLD', name: 'Netherlands', flag: '🇳🇱', iso: 'nl' },
  { id: 'ESP', name: 'Spain', flag: '🇪🇸', iso: 'es' },
  { id: 'BRA', name: 'Brazil', flag: '🇧🇷', iso: 'br' },
  { id: 'TUR', name: 'Turkey', flag: '🇹🇷', iso: 'tr' },
  { id: 'ZAF', name: 'South Africa', flag: '🇿🇦', iso: 'za' },
  { id: 'RUS', name: 'Russia', flag: '🇷🇺', iso: 'ru' },
  { id: 'KOR', name: 'South Korea', flag: '🇰🇷', iso: 'kr' },
  { id: 'SUI', name: 'Switzerland', flag: '🇨🇭', iso: 'ch' },
  { id: 'SWE', name: 'Sweden', flag: '🇸🇪', iso: 'se' },
  { id: 'NOR', name: 'Norway', flag: '🇳🇴', iso: 'no' },
  { id: 'DNK', name: 'Denmark', flag: '🇩🇰', iso: 'dk' },
  { id: 'PRT', name: 'Portugal', flag: '🇵🇹', iso: 'pt' },
  { id: 'NZL', name: 'New Zealand', flag: '🇳🇿', iso: 'nz' },
  { id: 'HKG', name: 'Hong Kong', flag: '🇭🇰', iso: 'hk' },
  { id: 'THA', name: 'Thailand', flag: '🇹🇭', iso: 'th' },
  { id: 'VNM', name: 'Vietnam', flag: '🇻🇳', iso: 'vn' },
  { id: 'IDN', name: 'Indonesia', flag: '🇮🇩', iso: 'id' },
  { id: 'PHL', name: 'Philippines', flag: '🇵🇭', iso: 'ph' }
];
